# Generated by Django 6.0 on 2025-12-09 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='departments',
            field=models.ManyToManyField(related_name='courses', to='app1.department'),
        ),
        migrations.AddField(
            model_name='course',
            name='semesters',
            field=models.ManyToManyField(related_name='courses', to='app1.semester'),
        ),
    ]
